### ISSUE TITLE
OFN record should not contain field IRI

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ofn-record-manager#1]
Forms should not contain field to enter IRI-s of a record. It should be generated automatically.

![Selection_371](https://user-images.githubusercontent.com/3962237/109123660-60c8f500-774a-11eb-85cd-96801da76601.jpg)

**Comment by psiotwo** [comment]
additionally, IRI field will go away

**Comment by psiotwo** [comment]
1h
