### ISSUE TITLE
Make categories of user fields (e.g. identifiers, metaquestions, type-questions ...)

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ofn-record-manager#33]
- categories: identifiers, description, metaquestions (technical question - "zobrazit více"), type-questions (type of section), temporal questions
- categories will not be shown in the UI
- categories will be used to order questions so that questions in one category are sequential.
- testing: in dev console one can check that a component has the appropriate category.

**Comment by psiotwo** [comment]
estimate: 3h
