### ISSUE TITLE
Respect expected length of user's output in length of answer fields

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ofn-record-manager#4]
Fields should be shorter in size for short answers and longer for long answer. E.g. "Nazev" vs. "Popis" in "Má otevírací dobu".

![Selection_373](https://user-images.githubusercontent.com/3962237/109123996-b7363380-774a-11eb-9e57-bd6572c4ad84.jpg)

**Comment by psiotwo** [comment]
- default input length is already predefined (the default should be datatype-specific).
- there will be option to specify longer/shorter fields based on the number of characters/digits.
- current bug: focus will be kept upon size change (small -> big, big-> small)
- update of the configuration forms for the 4 OFNs.

**Comment by psiotwo** [comment]
5h

**Comment by blcham** [comment]
Part that was not resolved:
https://github.com/opendata-mvcr/ofn-record-manager/issues/29
https://github.com/opendata-mvcr/ofn-record-manager/issues/30
