### ISSUE TITLE
Simplify UI towards less technical users

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ofn-record-manager#6]
- Dashboard should have one button for each managed OFN type
- Clicking to "OFN type button" from Dashboar should navigate to list of records where there will be button "Vytvořit"
- Button "Vytvorit" will navigate to creation of new record of particular OFN type. Thus section of OFN type should be removed from the edit-record screen.
- term "typ zaznamu" and "zaznam" should not occur in UI of regular user if possible (thus "Nazev zaznamu" -> "nazev", "Vytvorit zaznam" -> "Vytvorit", etc ...)

Additional notes: Dashboard with "OFN types" does not scale very well, which might be issue for "Admin". I suggest to keep list-of-all-records screen and generic "create-record" button on the dashboard of Admin user.

**Comment by psiotwo** [comment]
- detail screens parameterized by OFN type URL

**Comment by psiotwo** [comment]
16h
